backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - file: "src/pages/home/home.md"
        label: "Titulní strana"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/reward/reward.md"
        label: "Odměna advokáta"
        name: "reward"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "reward-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/reward"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/services/services.md"
        label: "Služby"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/services"}
          - {label: "Služby", name: "services", widget: "list", fields: [{label: "Nadpis", name: "title", widget: "string"}, {label: "Obsah", name: "content", widget: "string"}]}
  - name: "settings"
    label: "Nastavení"
    editor:
      preview: false
    files:
      - file: "src/settings/web-settings.md"
        label: "Web settings"
        name: "web-settings"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "settings-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "settings"}
          - {label: "Název webu", name: "title", widget: "string", default: "My new web"}